Vagrant.configure("2") do |config|
  config.vm.define "web0" do |web|
      web.vm.box = "ubuntu/xenial64"
      web.vm.hostname = "web0"
      web.vm.network "private_network", ip: "192.168.200.100"
      web.vm.provision "shell", path: "htop.sh"
      web.vm.provider :virtualbox do |vb|
        vb.customize [ 'modifyvm', :id, '--name', 'web0' ]
      end
  end
  config.vm.define "web1" do |web|
      web.vm.box = "ubuntu/xenial64"
      web.vm.hostname = "web1"
      web.vm.network "private_network", ip: "192.168.200.101"
      web.vm.provision "shell", path: "web.sh"
      web.vm.provider :virtualbox do |vb|
        vb.customize [ 'modifyvm', :id, '--name', 'web1' ]
      end
  end
end

